# Generated by Django 3.0.2 on 2020-01-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'Create User', 'verbose_name_plural': 'Create Users'},
        ),
    ]
