# Generated by Django 3.0.2 on 2020-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0003_message_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(db_index=True),
        ),
    ]
