# Generated by Django 3.0.2 on 2020-01-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0005_auto_20200122_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='entity',
            field=models.CharField(blank=True, max_length=60, verbose_name='entity'),
        ),
    ]
