# Generated by Django 3.0.2 on 2020-01-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0006_auto_20200122_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='entity',
        ),
    ]
