# Generated by Django 3.0.2 on 2020-01-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0008_auto_20200123_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
